Repository Occupational-Specialism-Team-Project/rza-past-exam-project, pull requests merged in 2025-02, with the labels that each got.

#22 Add a navbar, header, and footer
  db/rza_project.sql
  src/include/base.php
  src/include/footer.php
  src/include/header.php
  src/include/login.css
  src/index.php
  src/login.php
  src/logout.php
  src/sign_up.php
Labels: Enhancement

#19 Rza account registration
  db/rza_project.sql
  src/include/base.php
  src/include/login.css
  src/login.php
  src/logout.php
  src/sign_up.php
Labels: Requirement

#24 Update style guide
  documents/project/RZA Project Style Guide.md
  documents/project/RZA Project Style Guide.pdf
  documents/project/RZA Style Guide.md
  documents/project/RZA Style Guide.pdf
  src/example_template.php
  src/include/base.php
  src/include/connect.php
  src/include/footer.php
  src/include/utils.php
Labels: Debt

#26 Rza account registration 2
  src/include/login.css
  src/login.php
  src/logout.php
  src/sign_up.php
Labels: Requirement

#31 Add zoo booking, ticket display, verification, activation, and deactivation functionality
  db/rza_project.sql
  documents/project/Zoo Booking ERD.svg
  documents/project/Zoo Booking ERD.vpp
  documents/project/get_booked_days_algorithm.excalidraw
  src/get_booked_days.php
  src/include/base.php
  src/include/calendar.css
  src/include/calendar.js
  src/include/footer.php
  src/include/header.php
  src/include/settings.ini
  src/include/settings.php
  src/include/utils.php
  src/include/validation.js
  src/index.php
  src/tickets.php
  src/zoo_booking.php
Labels: Requirement

#32 Upload materials
  db/rza_project.sql
  documents/project/Crud_operation_flowchart.svg
  src/include/header.php
  src/upload_files.php
  src/uploads/.gitignore
Labels: Requirement
